#!/usr/bin/env python3
"""Tests for the `[diagram: <kind>]` blocks: the compile, the restyle, the gate, the gallery.

    python -m pytest skills/html-deliverable/test_diagrams.py

Two layers. The unit layer runs anywhere and needs no engine installed - it covers the outline
compiler, the sequence wrapper, the restyling pass and the lint gate. The render layer shells out
to d2 and graphviz and SKIPS with a named reason when they are not on this machine, because a
skill that refuses to run its own tests on a fresh checkout is a skill nobody keeps green.
"""

from __future__ import annotations

import re
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import build  # noqa: E402
import build_gallery  # noqa: E402
import lint  # noqa: E402

OUTLINE = """The system
  Capture
    Chat
  Route
    The board
"""
FLOW = "a: A capture lands\nb: The classifier reads it\na -> b: it is read\n"


def engine_ready(kind: str) -> str:
    """"" when the engine for `kind` is installed, otherwise the reason to skip."""
    spec = build.DIAGRAM_KINDS[kind]
    name = "d2" if spec["engine"] == "d2" else spec["layout"]
    try:
        build.diagram_binary(name, spec["engine"])
    except SystemExit as missing:
        return str(missing)
    return ""


def page(body: str) -> str:
    """A minimal page that satisfies every OTHER lint rule, so one check is under test."""
    return (
        '<!doctype html><html lang="en" data-theme="light" data-look="tint"><head><style>'
        ":root{--wrap-w:1080px}\n/* requestAnimationFrame */\n</style></head><body>"
        '<button class="grip l"></button><button class="grip r"></button>'
        '<nav id="sidenav"><button data-target="s1">A</button><button data-target="s2">B</button></nav>'
        f'<div class="wrap">{body}</div>'
        "<script>requestAnimationFrame(function(){});</script></body></html>"
    )


class TheOutlineCompiler(unittest.TestCase):
    def test_two_spaces_is_one_level(self):
        self.assertEqual(
            build.outline_rows("A\n  B\n    C\n  D\n"),
            [(0, "A"), (1, "B"), (2, "C"), (1, "D")],
        )

    def test_a_tab_bullets_blanks_and_comments_all_read(self):
        rows = build.outline_rows("A\n\t- B\n\n  # a note\n  * C\n")
        self.assertEqual(rows, [(0, "A"), (1, "B"), (1, "C")])

    def test_the_dot_carries_the_parent_edges_and_nothing_else(self):
        dot = build.outline_to_dot(OUTLINE, "twopi")
        self.assertIn("n0 -> n1;", dot)   # The system -> Capture
        self.assertIn("n1 -> n2;", dot)   # Capture -> Chat
        self.assertIn("n0 -> n3;", dot)   # The system -> Route  (not Chat -> Route)
        self.assertNotIn("n2 -> n3;", dot, "the outline popped back a level and the edge did not")

    def test_the_ground_polygon_is_never_painted(self):
        """Graphviz's white background renders as a white card behind a dark-theme diagram."""
        for layout in ("twopi", "dot"):
            self.assertIn("bgcolor=transparent;", build.outline_to_dot(OUTLINE, layout))

    def test_no_color_is_baked_into_the_dot(self):
        """A color in the DOT would beat the house token in one of the two themes."""
        dot = build.outline_to_dot(OUTLINE, "dot")
        self.assertNotIn("fillcolor", dot)
        self.assertNotIn("#", dot)

    def test_a_quote_in_a_label_cannot_break_out(self):
        dot = build.outline_to_dot('He said "go"\n  and went\n', "dot")
        self.assertIn(r'label="He said \"go\""', dot)

    def test_an_empty_outline_says_so(self):
        with self.assertRaises(SystemExit):
            build.outline_to_dot("\n\n", "dot")


class TheSequenceWrapper(unittest.TestCase):
    def test_plain_messages_are_wrapped_and_the_container_is_unlabelled(self):
        wrapped = build.d2_sequence_source("A -> B: hi\n")
        self.assertIn("shape: sequence_diagram", wrapped)
        self.assertIn('label: ""', wrapped)
        self.assertIn("  A -> B: hi", wrapped)

    def test_a_source_that_already_declares_the_shape_is_left_alone(self):
        own = "mine: {\n  shape: sequence_diagram\n  A -> B: hi\n}"
        self.assertEqual(build.d2_sequence_source(own), own)


class TheRestyling(unittest.TestCase):
    RAW = (
        '<?xml version="1.0"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://x/svg11.dtd">\n'
        '<!-- Generated by something -->\n'
        '<svg width="400pt" height="300pt" viewBox="0 0 400 300">'
        "<style>@font-face { font-family: d2-font; src: url(data:font/woff;base64,AAAA); }\n"
        '.t { font-family: "d2-font"; }</style>'
        '<g class="node"><polygon fill="white" stroke="black"/><text>Box</text></g></svg>'
    )

    def setUp(self):
        self.out = build.restyle_svg(self.RAW, "graphviz", "u1")

    def test_the_standalone_wrapper_is_gone(self):
        self.assertNotIn("<?xml", self.out)
        self.assertNotIn("<!DOCTYPE", self.out)
        self.assertNotIn("Generated by", self.out)

    def test_the_embedded_font_and_its_rules_are_gone(self):
        self.assertNotIn("@font-face", self.out)
        self.assertNotIn("font-family", self.out)
        self.assertNotIn("base64", self.out)

    def test_the_fixed_pixel_size_is_dropped_but_the_viewbox_stays(self):
        self.assertNotIn('width="400pt"', self.out)
        self.assertNotIn('height="300pt"', self.out)
        self.assertIn('viewBox="0 0 400 300"', self.out)

    def test_the_wrapper_names_the_engine_and_the_block(self):
        self.assertIn('<div class="dgm-art" id="u1" data-engine="graphviz">', self.out)
        self.assertIn('class="dgm-svg"', self.out)

    def test_the_geometry_and_the_engine_classes_survive(self):
        """The recolor is CSS over presentation attributes, so the classes must still be there."""
        self.assertIn('class="node"', self.out)
        self.assertIn('fill="white"', self.out)


class TheHint(unittest.TestCase):
    def test_a_kind_with_no_caption(self):
        match = build.DIAGRAM_HINT_RE.search("<p>[diagram: tree]</p>\n<pre><code>A\n</code></pre>")
        self.assertEqual((match.group(1), match.group(2)), ("tree", None))

    def test_a_kind_with_a_caption(self):
        match = build.DIAGRAM_HINT_RE.search(
            "<p>[diagram: mindmap | What it holds]</p>\n<pre><code>A\n</code></pre>"
        )
        self.assertEqual((match.group(1), match.group(2)), ("mindmap", "What it holds"))

    def test_an_unknown_kind_names_the_kinds_that_exist(self):
        with self.assertRaises(SystemExit) as raised:
            build.diagram_blocks("<p>[diagram: gantt]</p>\n<pre><code>A\n</code></pre>")
        self.assertIn("flowchart", str(raised.exception))
        self.assertIn("mindmap", str(raised.exception))

    def test_a_fence_with_no_hint_is_left_as_a_code_block(self):
        source = "<pre><code>a -&gt; b\n</code></pre>"
        out, used = build.diagram_blocks(source)
        self.assertEqual((out, used), (source, False))


class TheMissingEngineMessage(unittest.TestCase):
    def test_it_names_the_install_command_rather_than_a_stack_trace(self):
        with self.assertRaises(SystemExit) as raised:
            build.diagram_binary("no-such-engine-binary", "d2")
        message = str(raised.exception)
        self.assertIn("winget install Terrastruct.D2", message)
        self.assertIn("no-such-engine-binary", message)


class TheLintGate(unittest.TestCase):
    """A diagram in a house deliverable is in the file, not on the network."""

    def failures(self, body: str) -> list[str]:
        return lint.check(page(body), money=False, allow_commands=True)[0]

    def test_an_image_of_a_diagram_fails(self):
        failures = self.failures('<section id="s1"><img src="https://example.com/chart.png"></section>')
        self.assertTrue(any("does not carry" in f for f in failures), failures)

    def test_a_relative_image_fails_too(self):
        failures = self.failures('<section id="s1"><img src="chart.png"></section>')
        self.assertTrue(any("does not carry" in f for f in failures), failures)

    def test_a_data_uri_image_is_fine(self):
        failures = self.failures('<section id="s1"><img src="data:image/png;base64,AAAA"></section>')
        self.assertEqual([f for f in failures if "does not carry" in f], [], failures)

    def test_a_cdn_diagram_script_fails(self):
        failures = self.failures(
            '<section id="s1"><script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script></section>'
        )
        self.assertTrue(any("PRE-RENDERED" in f for f in failures), failures)

    def test_an_unrendered_diagram_element_fails(self):
        failures = self.failures('<section id="s1"><div class="mermaid">graph TD; A-->B;</div></section>')
        self.assertTrue(any("unrendered diagram element" in f for f in failures), failures)

    def test_a_runtime_initializer_fails(self):
        failures = self.failures('<section id="s1"><p>x</p></section><script>mermaid.initialize({});</script>')
        self.assertTrue(any("initializer" in f for f in failures), failures)

    def test_a_remote_frame_fails(self):
        failures = self.failures('<section id="s1"><iframe src="https://example.com/d"></iframe></section>')
        self.assertTrue(any("remote frame" in f for f in failures), failures)

    def test_prose_naming_an_engine_is_not_a_breach_of_the_rule(self):
        """The gallery and this skill's own pages talk about these engines by name."""
        failures = self.failures(
            '<section id="s1"><p>We compared Mermaid, Graphviz and Kroki before choosing.</p></section>'
        )
        self.assertEqual([f for f in failures if "PRE-RENDERED" in f], [], failures)


class TheRenderedDiagrams(unittest.TestCase):
    """The layer that actually shells out. Skipped, with the reason, when an engine is missing."""

    def render(self, kind: str, source: str, uid: str = "t1") -> str:
        reason = engine_ready(kind)
        if reason:
            self.skipTest(reason)
        return build.restyle_svg(build.run_engine(kind, source, uid), build.DIAGRAM_KINDS[kind]["engine"], uid)

    def test_every_kind_renders_to_inline_svg_that_fetches_nothing(self):
        for kind, source in (
            ("flowchart", FLOW),
            ("sequence", "A -> B: a question\nB -> A: the answer\n"),
            ("mindmap", OUTLINE),
            ("tree", OUTLINE),
        ):
            with self.subTest(kind=kind):
                art = self.render(kind, source)
                self.assertIn("<svg", art)
                self.assertIn(f'data-engine="{build.DIAGRAM_KINDS[kind]["engine"]}"', art)
                self.assertNotIn("<img", art)
                self.assertNotIn("<script", art)
                self.assertNotIn("http://", art.replace("http://www.w3.org", ""))
                self.assertNotIn("https://", art)

    def test_the_labels_the_author_wrote_are_in_the_picture(self):
        art = self.render("flowchart", FLOW)
        self.assertIn("A capture lands", art)
        self.assertIn("The classifier reads it", art)

    def test_two_diagrams_on_one_page_do_not_share_an_id(self):
        reason = engine_ready("flowchart")
        if reason:
            self.skipTest(reason)
        source = ("<p>[diagram: flowchart]</p>\n<pre><code>a -&gt; b\n</code></pre>\n"
                  "<p>[diagram: flowchart]</p>\n<pre><code>c -&gt; d\n</code></pre>")
        out, used = build.diagram_blocks(source, prefix="p-")
        self.assertTrue(used)
        ids = re.findall(r'class="dgm-art" id="([^"]+)"', out)
        self.assertEqual(ids, ["p-dgm1", "p-dgm2"])
        markers = set(re.findall(r'id="(mk-[^"]+)"', out))
        self.assertEqual(len(markers), len(set(markers)), "two svgs on one page reused an id")

    def test_a_built_page_ships_the_styles_carries_no_network_call_and_passes_the_lint(self):
        reason = engine_ready("flowchart")
        if reason:
            self.skipTest(reason)
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "d.md"
            source.write_text(
                "# A page with a picture\n\nThe lead paragraph.\n\n## The path\n\n"
                "[diagram: flowchart | How it moves]\n\n```\n" + FLOW + "```\n\n"
                "## After\n\nMore words, at https://example.com/one and https://example.com/two .\n",
                encoding="utf-8",
            )
            out = source.with_suffix(".html")
            self.assertEqual(build.main([str(source), str(out)]), 0)
            html = out.read_text(encoding="utf-8")
        self.assertIn(".dgm-art", html, "the diagram CSS did not ship with the page")
        self.assertIn('<figure class="dgm"', html)
        self.assertIn("<figcaption>How it moves</figcaption>", html)
        self.assertEqual(lint.check(html, money=False, allow_commands=True)[0], [])

    def test_the_caption_becomes_the_accessible_name(self):
        reason = engine_ready("tree")
        if reason:
            self.skipTest(reason)
        out, _ = build.diagram_blocks(
            "<p>[diagram: tree | The shape of it]</p>\n<pre><code>A\n  B\n</code></pre>"
        )
        self.assertIn('role="img"', out)
        self.assertIn('aria-label="The shape of it"', out)


class TheGalleryCarriesOneDemoPerKind(unittest.TestCase):
    def setUp(self):
        self.catalogue = {c.cid: c for c in build_gallery.COMPONENTS}
        self.gallery = (HERE / "components.html").read_text(encoding="utf-8")

    def test_one_component_per_kind(self):
        for kind in build.DIAGRAM_KINDS:
            with self.subTest(kind=kind):
                component = self.catalogue.get(f"diagram-{kind}")
                self.assertIsNotNone(component, f"the gallery has no demo for [diagram: {kind}]")
                self.assertEqual(component.diagram[0], kind)

    def test_the_built_gallery_carries_every_demo_and_its_markdown(self):
        for kind in build.DIAGRAM_KINDS:
            with self.subTest(kind=kind):
                self.assertIn(f'id="c-diagram-{kind}"', self.gallery, "rebuild the gallery")
                self.assertIn(f"[diagram: {kind} |", self.gallery, "the copy-paste markdown is missing")

    def test_the_gallery_ships_the_diagram_styles_once(self):
        self.assertIn(".dgm-art[data-engine=", self.gallery)
        self.assertEqual(self.gallery.count(".dgm-art{background:var(--panel-2)"), 1)

    def test_the_gallery_diagrams_are_real_inline_svg(self):
        self.assertGreaterEqual(self.gallery.count('class="dgm-art"'), len(build.DIAGRAM_KINDS))


if __name__ == "__main__":
    unittest.main(verbosity=2)
